# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300'
- script: chmod +x ./build.sh
- bash: |
    ./build.sh
  displayName: 'build script'
